#!/usr/bin/env bash
# 4ndr0666
#            # === GTKTHEMES === #
# Description: Sets GTK Themes, Icons, Cursor and Fonts

# === COLORFUL-DARK THEME === #
THEME='Colorful-Dark'
ICONS='Colorful-Dark-Icons'
FONT='Noto Sans 9'
CURSOR='Bibata-Modern_Ice'
SCHEMA='gsettings set org.gnome.desktop.interface'
apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}
apply_themes


# === SWEET-V40 THEME === #
#
# usage: import-gsettings
# config="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini"
# if [ ! -f "$config" ]; then exit 1; fi

# gnome_schema="org.gnome.desktop.interface"
# gtk_theme="Sweet-v40"
# icon_theme="Colorful-Dark-Icons"
# cursor_theme="Bibata-Modern-Ice"
# font_name="Noto Sans 9"
# gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
# gsettings set "$gnome_schema" icon-theme "$icon_theme"
# gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
# gsettings set "$gnome_schema" font-name "$font_name"
