repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-executables-have-shebangs  
  - repo: local
    hooks:
      - id: codex-clean
        name: Clean merge artifacts
        entry: 0-tests/codex-merge-clean.sh
        language: script
        files: \.(sh|lua|md|txt)$
      - id: shellcheck
        name: ShellCheck (bash)
        entry: shellcheck -x
        language: system
        types: [shell]
