#!/bin/bash

echo "Disabling IPv6..."

# Disable IPv6 globally
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1

# Disable IPv6 on each interface
for interface in $(ls /proc/sys/net/ipv6/conf/); do
    sysctl -w net.ipv6.conf.$interface.disable_ipv6=1
done

echo "IPv6 disabled successfully."
