#!/bin/bash

# --- // AUTO_ESCALATE:
if [ "$(id -u)" -ne 0 ]; then
      sudo "$0" "$@"
    exit $?
fi

echo "Enabling IPv6..."

# Enable IPv6 globally
sysctl -w net.ipv6.conf.all.disable_ipv6=0
sysctl -w net.ipv6.conf.default.disable_ipv6=0

# Enable IPv6 on each interface
for interface in $(ls /proc/sys/net/ipv6/conf/); do
    sysctl -w net.ipv6.conf.$interface.disable_ipv6=0
done

echo "IPv6 enabled successfully."
