#!/bin/bash
#File: ufwon
#Author: 4ndr0666
#Edited: 04-11-2024
#
# --- // UFWON // ========


# --- // AUTO_ESCALATE:
if [ "$(id -u)" -ne 0 ]; then
  sudo "$0" "$@"
  exit $?
fi

ufw_config() {
    echo  "Configuring UFW..."
    sleep 2
    ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing
    ufw default deny incoming v6
    ufw defulat deny outgoing v6
    ufw limit 22/tcp # SSH with rate limiting
    ufw allow 6800/tcp # Aria2c
    ufw allow 37295/tcp # VPN
    ufw allow from 192.168.1.0/24 to any port 9666
    ufw allow from 192.168.1.0/24 to any port 9665
    ufw allow from 192.168.1.0/24 to any port 36501
    ufw --force enable
    ufw status verbose
}

sysctl_config() {
    echo "Checking sysctl configuration..."
    sleep 2
    declare -A sysctl_settings=(
        ["kernel.modules_disabled"]="1"
        ["vm.swappiness"]="10"
        ["kernel.nmi_watchdog"]="0"
        ["kernel.unprivileged_userns_clone"]="1"
        ["kernel.printk"]="3 3 3 3"
    )

    # Apply sysctl settings
#    for key in "${!sysctl_settings[@]}"; do
#        sysctl -w "$key=${sysctl_settings[$key]}"
#        echo "$key = ${sysctl_settings[$key]}" >> /etc/sysctl.conf
#    done

     # Append settings only if they don't exist
    while read -r line; do
        grep -qF -- "$line" /etc/sysctl.conf || echo "$line" >> /etc/sysctl.conf
    done <<< "$SYSCTL_SETTINGS"

    sysctl -p # Reload sysctl settings

    # Prevent IP spoofing
    HOST_CONF_CONTENT="\nmulti on"
    echo -e "$HOST_CONF_CONTENT" > /etc/host.conf
    echo "Updated /etc/host.conf to prevent IP spoofing."
}

main() {
    echo  "Initiating system hardening..."
    sleep 1

    ufw_config
    sysctl_config

    echo  "System hardening complete."
    sleep 1

    echo "### ============================== // LISTENING PORTS // ============================== ###"
    netstat -tunlp
    sleep 3

    echo "### ============ // UFW SUMMARY // ============ ###"
    ufw status numbered
    sleep 2
}

main "$@"
