#!/bin/bash
# Script Name: ufwon
# Description: Automatically escalates privileges sets ufw, sysctl and hosts.
# Author: 4ndr0666
# Edited: 02-06-2024

if [ "$(id -u)" -ne 0 ]; then
  sudo "$0" "$@"
  exit $?
fi

echo -e "\033[34m"
cat << "EOF"
#  ___________.__                              .__  .__              .__
#  \_   _____/|__|______   ______  _  _______  |  | |  |        _____|  |__
#   |    __)  |  \_  __ \_/ __ \ \/ \/ /\__  \ |  | |  |       /  ___/  |  \
#   |     \   |  ||  | \/\  ___/\     /  / __ \|  |_|  |__     \___ \|   Y  \
#   \___  /   |__||__|    \___  >\/\_/  (____  /____/____/ /\ /____  >___|  /
#       \/                    \/             \/            \/      \/     \/
EOF
echo -e "\033[0m"
sleep 1

# --- Function to configure UFW
ufw_config() {
  echo "Configuring UFW..."
  sleep 2
  ufw --force reset
  ufw limit 22/tcp
  ufw allow 80/tcp
  ufw allow 443/tcp
  ufw allow 6341/tcp # Megasync
  ufw allow 6800/tcp # Aria2c
  ufw default deny incoming
  ufw default allow outgoing
  ufw default deny incoming v6
  ufw default allow outgoing v6
  ufw enable
}

# --- Harden /etc/sysctl.conf
sysctl_config() {
    echo "Checking sysctl configuration..."
    sleep 2
    SYSCTL_SETTINGS="
sudo sysctl kernel.modules_disabled=1
sudo sysctl -a
sudo sysctl -A
sudo sysctl mib
sudo sysctl net.ipv4.conf.all.rp_filter
sudo sysctl -a --pattern 'net.ipv4.conf.(eth|wlan)0.arp'
kernel.sysrq = 1
vm.swappiness=10
kernel.nmi_watchdog = 0
kernel.unprivileged_userns_clone=1
kernel.printk = 3 3 3 3
"
    # Append settings only if they don't exist
    while read -r line; do
        grep -qF -- "$line" /etc/sysctl.conf || echo "$line" >> /etc/sysctl.conf
    done <<< "$SYSCTL_SETTINGS"

    sysctl -p

    # Prevent IP Spoofs - only update if necessary
    HOST_CONF_CONTENT="order bind,hosts\nmulti on"
    if ! grep -qF "$HOST_CONF_CONTENT" /etc/host.conf; then
        echo "Updating host.conf to prevent IP spoofs..."
        echo -e "$HOST_CONF_CONTENT" > /etc/host.conf
    fi
}

# ----------------------------------------------------------------------------// SCRIPT_LOGIC //:
echo "Initiating system hardening..."
sleep 2
ufw_config
sysctl_config
sleep 1

# --- Portscan Summary:
echo "### ============================== // LISTENING PORTS // ============================== ###"
netstat -tunlp
sleep 3

# --- UFW Status:
echo "### ============ // UFW SUMMARY // ============ ###"
ufw status numbered
sleep 2
