#!/bin/bash
# Script Name: ufwon
# Description: Automatically escalates privileges, sets UFW, sysctl, and hosts for enhanced security.
# Author: 4ndr0666
# Edited: 03-01-2024

# Check for root privileges and re-execute with sudo if necessary
if [ "$(id -u)" -ne 0 ]; then
    echo "Re-running script with sudo..."
    sudo "$0" "$@"
    exit $?
fi

# Configuration function for UFW
ufw_config() {
    echo -e "\033[34mConfiguring UFW...\033[0m"
    sleep 2
    ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing

    # Essential services
    ufw limit 22/tcp # SSH with rate limiting
    ufw allow 80/tcp # HTTP
    ufw allow 443/tcp # HTTPS

    # Local network services
    ufw allow from 192.168.1.0/24 to any port 9666
    ufw allow from 192.168.1.0/24 to any port 9665
    ufw allow from 192.168.1.0/24 to any port 36501

    # Enable UFW with logging
    ufw logging on
    ufw --force enable
    ufw status verbose
}

# Configuration function for sysctl
sysctl_config() {
    echo -e "\033[34mChecking sysctl configuration...\033[0m"
    sleep 2

    # Define desired sysctl settings
    declare -A sysctl_settings=(
        ["kernel.modules_disabled"]="1"
        ["vm.swappiness"]="10"
        ["kernel.nmi_watchdog"]="0"
        ["kernel.unprivileged_userns_clone"]="1"
        ["kernel.printk"]="3 3 3 3"
    )

    # Apply sysctl settings
    for key in "${!sysctl_settings[@]}"; do
        sysctl -w "$key=${sysctl_settings[$key]}"
        echo "$key = ${sysctl_settings[$key]}" >> /etc/sysctl.conf
    done

    sysctl -p # Reload sysctl settings

    # Prevent IP spoofing
    HOST_CONF_CONTENT="order bind,hosts\nmulti on"
    echo -e "$HOST_CONF_CONTENT" > /etc/host.conf
    echo "Updated /etc/host.conf to prevent IP spoofing."
}

# Main script execution
main() {
    echo -e "\033[34mInitiating system hardening...\033[0m"
    sleep 1

    ufw_config
    sysctl_config

    echo -e "\033[34mSystem hardening complete.\033[0m"
    sleep 1

    # Display listening ports and UFW status as a summary
    echo "### ============================== // LISTENING PORTS // ============================== ###"
    netstat -tunlp
    sleep 3

    echo "### ============ // UFW SUMMARY // ============ ###"
    ufw status numbered
    sleep 2
}

main "$@"
