#!/usr/bin/env bash
# Author: 4ndr0666
# ==================== // BRAVEBACKGROUNDED //
## Description: File: $HOME/.local/bin/bravebackgrounded
#                     Optimized launcher for brave-beta.
# ---------------------------------------------------

BRAVE_BIN="/usr/bin/brave-beta"

"$BRAVE_BIN" \
  --allowlisted-extension-id=clngdbkpkpeebahjckkjfobafhncgmne \
  --disable-crash-reporter \
  --ozone-platform=wayland \
  --disk-cache-size=104857600 \
  --extensions-process-limit=1 \
  --enable-gpu-rasterization \
  --enable-zero-copy \
  --enable-features=ProactiveTabFreezeAndDiscard \
  "$@" &
