#!/bin/sh
# Version: 1.0.0
# Author: 4ndr0666
set -eu
# ========================== // DMENUHANDLER //
## Description: Feed a URL or file path to the dmenu
#               and choose and app to open it with.
# Usage:
#       <Super> + <KEY_F9>
# -------------------------------------

## Dynamic Clipboard

clip() { command -v wl-copy >/dev/null && wl-copy || xclip -selection clipboard; }

## URL & File Path

feed="${1:-$(printf '' | dmenu -p 'Paste URL or file path')}"

choice=$(printf "copy url\nytf\nnsxiv\nsetbg\nPDF\nbrowser\nlynx\nvim\nmpv\nmpv loop\nmpv float\nqueue download\nqueue yt-dlp\nqueue yt-dlp audio" |
         dmenu -i -p "Open it with?")

case "$choice" in
    copy*)
        printf '%s' "$feed" | clip
        ;;

    ytf)
        setsid -f "$TERMINAL" -e zsh -c "ytf '$feed'; read -r -p '\nENTER to close…'" ;;
        ;;

    mpv)
        setsid -f mpv -quiet "$feed" >/dev/null 2>&1
        ;;

    "mpv loop")
        setsid -f mpv -quiet --loop "$feed" >/dev/null 2>&1
        ;;

    "mpv float")
        setsid -f "$TERMINAL" -e mpv --geometry=30% --title="mpvfloat" "$feed" >/dev/null 2>&1
        ;;

    "queue yt-dlp")
        qndl "$feed" >/dev/null 2>&1
        ;;

    "queue yt-dlp audio")
        qndl "$feed" 'yt-dlp -o "%(title)s.%(ext)s" -f bestaudio --embed-metadata --restrict-filenames'
        ;;

    "queue download")
        qndl "$feed" 'curl -LO' >/dev/null 2>&1
        ;;

    PDF)
        tmpfile="/tmp/$(echo "$feed" | sed "s|.*/||;s/%20/ /g")"
        curl -sL "$feed" > "$tmpfile" && zathura "$tmpfile" >/dev/null 2>&1
        ;;

    nsxiv)
        tmpfile="/tmp/$(echo "$feed" | sed "s|.*/||;s/%20/ /g")"
        curl -sL "$feed" > "$tmpfile" && nsxiv -a "$tmpfile" >/dev/null 2>&1
        ;;

    vim)
        tmpfile="/tmp/$(echo "$feed" | sed "s|.*/||;s/%20/ /g")"
        curl -sL "$feed" > "$tmpfile" && setsid -f "$TERMINAL" -e "$EDITOR" "$tmpfile" >/dev/null 2>&1
        ;;

    setbg)
        curl -L "$feed" > "$XDG_CACHE_HOME/pic" && swaybg -i "$XDG_CACHE_HOME/pic" --mode fill >/dev/null 2>&1
        ;;

    browser)
        setsid -f "$BROWSER" "$feed" >/dev/null 2>&1
        ;;

    lynx)
        setsid -f "$TERMINAL" -e lynx "$feed" >/dev/null 2>&1
        ;;
esac
