#!/bin/sh

#File: $HOME/.config/hypr/hyprstart
#Author: 4ndr0666
#Edited: 04-10-24
#This is the be sourced with hyprland to setup the environment and needs to be placed in /usr/local/bin.
#
# --- // hyprstart // ========


cd ~
# --- // DEFAULT_PROGS:
export XCURSOR_SIZE=24
export MICRO_TRUECOLOR=1
export EDITOR=/usr/bin/nvim
export TERM=alacritty
export BROWSER=brave

# --- // DESKTOP:
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=hyprland
export XDG_CURRENT_DESKTOP=hyprland

# --- // WAYLAND_VARIABLES:
export MOZ_ENABLE_WAYLAND=1             # only start firefox in wayland mode and no other GTK apps
export MOZ_DBUS_REMOTE=1                # fixes firefox is already running, but is not responding
export MOZ_WAYLAND_USE_VAAPI=1
export GDK_BACKEND=wayland             # this can prevent programs from starting (e.g. chromium and electron apps). therefore, this should be set per app instead of globally.
#export CLUTTER_BACKEND=wayland          # this can prevent programs from starting. therefore, this should be set per app instead of globally.

export ECORE_EVAS_ENGINE=wayland-egl
export ELM_ENGINE=wayland_egl
export _JAVA_AWT_WM_NONREPARENTING=1
export NO_AT_BRIDGE=1
export BEMENU_BACKEND=wayland

export SDL_VIDEODRIVER=wayland           # this can prevent programs from starting old sdl games. therefore, this should be set per app instead of globally.
export QT_QPA_PLATFORM=wayland

export FZF_DEFAULT_OPTS=" \
--color=bg+:-1,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#a6e3a1,prompt:#cba6f7,hl+:#f38ba8"

if ! command -v wl-copy &> /dev/null; then                 #Checks for wl-clpy (Wayland clipboard)
  echo "wl-clipboard is required but not installed."
  return 1
fi
#alias sudo_wayland='/usr/local/bin/wayland_root_access.sh' # Wayland
#xhost +SI:localuser:andro                                 # For X on wayland
#xhost +SI:localuser:root                                  # For X on wayland


# --- // FILE_SOURCING_&_PLUGINS // ======== 
# Above is the generally accepted stable setup for hyprland going around. I 
# recommend not editing it directly and instead sourcing your customizations. 
# I have defined the source file for you here at $HOME/.config/hypr/hyprstart:

hyprstart="$HOME/.config/hypr/hyprstart"
if [ -x "$hyprstart" ]; then
    . "$hyprstart"
else
    echo "$hyprstart does not exist or is not executable."
fi

exec Hyprland
