name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  env-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Bash and jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up XDG + PYENV/PIPX/POETRY env
        run: |
          export XDG_CONFIG_HOME=$HOME/.config
          export XDG_DATA_HOME=$HOME/.local/share
          export XDG_CACHE_HOME=$HOME/.cache
          export PYENV_ROOT=$XDG_DATA_HOME/pyenv
          export PIPX_HOME=$XDG_DATA_HOME/pipx
          export PIPX_BIN_DIR=$PIPX_HOME/bin
          export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PIPX_BIN_DIR:$PATH"

      - name: Install pyenv
        run: curl https://pyenv.run | bash

      - name: Install pipx
        run: python3 -m pip install --user pipx

      - name: Install Poetry
        run: pipx install poetry

      - name: ShellCheck
        run: shellcheck $(find . -type f -name '*.sh')

      - name: Run Environment Verification
        run: bash ./test/src/verify_environment.sh --report

      - name: Run Final Audit
        run: bash ./test/src/final_audit.sh --report
