# .github/workflows/shellcheck.yml
name: "Trigger: Push action"

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
